# Generated by Django 4.2.5 on 2023-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarWash_App', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/'),
        ),
    ]
