# Generated by Django 4.2.5 on 2023-10-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarWash_App', '0004_alter_blogpost_options_blogpost_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
